### ISSUE TITLE
Features and Maintenance Request

### ISSUE THREAD

**Issue by v1k0d3n** [openshifttips/web#49]
Hello maintainers! I wanted to start a discussion about maintenance and some potential improvements to the site. In full transparency I reached out to @e-minguez, asking if I could maintain this repository if nobody else is interested for the purposes of keeping the content fresh/new.

I'm on the Telco Tiger Team inside of Red Hat, and really I like that this site matches closely with what some other teams are doing (the OCS/ODF team comes to mind as an example: [https://red-hat-storage.github.io](https://red-hat-storage.github.io/ocs-training/training/index.html)).

I come across a _lot_ of use cases in the field that I think would be really nice to continually add to the site. I would probably even redirect one of my domains here (maybe something like [tips.ocp.run](tips.ocp.run)?), if I could keep the content up to date relevant with future releases, etc. But I wanted to bring this request up publicly for a discussion. One of my other blogs is [cloudcult.dev](cloudcult.dev), and I have a lot of content to add to it soon. I've been really busy this year working with some great customers, and it's just a matter of getting some additional use cases on the site. 

Any thoughts or considerations?

**Comment by iranzo** [comment]
Yes, feel free to submit PR's and we'll be reviewing and adding them, so that's a perfect fit!

**Comment by e-minguez** [comment]
I'm not longer a Red Hat employee so I guess it is ok to transfer it. 
The domain is owned by Red Hat but they pointed it to use my own DNS (I'm using cloud flare right now).

Pinging @javipolo & @iranzo as they are supposed to be the maintainers now :)
