### ISSUE TITLE
example in documentation faulty

### ISSUE THREAD

**Issue by shotty01** [openshifttips/web#56]
on this page
https://openshift.tips/cleanup/
in the example for the section
- Change the image GC thresholds
the values for ImageGCHighThresholdPercent and ImageGCLowThresholdPercent are switched (high has to be higher than low)
copying this to the kubeletconfig causes kubelet not to start anymore, and it was a hassle to resolve, so please fix it for all the tired devops people who just copy values out of examples ;)

**Comment by iranzo** [comment]
Can you check PR https://github.com/openshifttips/web/pull/57 ? 

Thanks
